# FreeRADIUS clients.conf — RP06 IRIS Nice
# Equipements Cisco autorises

client SW2-IRIS {
    ipaddr          = 192.168.50.2
    secret          = RadiusSW_IRIS_2026!
    shortname       = SW2-IRIS
    nas_type        = cisco
}

client RT2-IRIS {
    ipaddr          = 192.168.50.1
    secret          = RadiusRTR_IRIS_2026!
    shortname       = RT2-IRIS
    nas_type        = cisco
}

client AP-IRIS {
    ipaddr          = 192.168.50.24
    secret          = RadiusAP_IRIS_2026!
    shortname       = AP-IRIS
    nas_type        = cisco
}